version: '3.9'
services:
  db:
    image: postgres:14.3
    restart: always
    volumes:
      - ./.database/data:/var/lib/postgresql/data
      - ./.database/backups:/backups
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8081:8080