version: '3.9'
services:
  db:
    image: postgres:14.3
    restart: always
    volumes:
      - ./.database/data:/var/lib/postgresql/data
      - ./.database/backups:/backups
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8081:8080
  
  translater:
    image: mozilla/translation-service:latest
    restart: always
    ports: 
      - 8082:8082
    environment:
      PORT: 8082
    volumes:
      - ./firefox-translations-models/models/dev:/models

  back:
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    build:
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}

      TRANSLATER_HOST: ${TRANSLATER_HOST}
      TRANSLATER_PORT: ${TRANSLATER_PORT}
      SECRET: ${SECRET}
      MONKEY_LEARN_API: ${MONKEY_LEARN_API}
    ports:
      - 8000:8000

    depends_on:
      - db
      - translater