"""empty message

Revision ID: 1a37addf2c9d
Revises: 
Create Date: 2022-10-01 16:12:58.121380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a37addf2c9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user'))
    )
    op.create_index(op.f('ix__user__email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix__user__id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__user__id'), table_name='user')
    op.drop_index(op.f('ix__user__email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
