"""empty message

Revision ID: 6a11acbb6efc
Revises: ae9f42ed7fd6
Create Date: 2022-10-02 07:28:31.181673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a11acbb6efc'
down_revision = 'ae9f42ed7fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favourite_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favourite_user_id'], ['user.id'], name=op.f('fk__favourite_user__favourite_user_id__user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__favourite_user__user_id__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__favourite_user'))
    )
    op.create_index(op.f('ix__favourite_user__favourite_user_id'), 'favourite_user', ['favourite_user_id'], unique=False)
    op.create_index(op.f('ix__favourite_user__id'), 'favourite_user', ['id'], unique=False)
    op.create_index(op.f('ix__favourite_user__user_id'), 'favourite_user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__favourite_user__user_id'), table_name='favourite_user')
    op.drop_index(op.f('ix__favourite_user__id'), table_name='favourite_user')
    op.drop_index(op.f('ix__favourite_user__favourite_user_id'), table_name='favourite_user')
    op.drop_table('favourite_user')
    # ### end Alembic commands ###
