"""empty message

Revision ID: 7266b1841dc1
Revises: 505614d54094
Create Date: 2022-10-01 17:44:40.530344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7266b1841dc1'
down_revision = '505614d54094'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotion.id'], name=op.f('fk__calendar_day__emotion_id__emotion')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__calendar_day__user_id__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__calendar_day'))
    )
    op.create_index(op.f('ix__calendar_day__day'), 'calendar_day', ['day'], unique=False)
    op.create_index(op.f('ix__calendar_day__emotion_id'), 'calendar_day', ['emotion_id'], unique=False)
    op.create_index(op.f('ix__calendar_day__id'), 'calendar_day', ['id'], unique=False)
    op.create_index(op.f('ix__calendar_day__user_id'), 'calendar_day', ['user_id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotion.id'], name=op.f('fk__status__emotion_id__emotion')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__status__user_id__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__status'))
    )
    op.create_index(op.f('ix__status__emotion_id'), 'status', ['emotion_id'], unique=False)
    op.create_index(op.f('ix__status__id'), 'status', ['id'], unique=False)
    op.create_index(op.f('ix__status__user_id'), 'status', ['user_id'], unique=False)
    op.create_index(op.f('ix__status__value'), 'status', ['value'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotion.id'], name=op.f('fk__comment__emotion_id__emotion')),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk__comment__post_id__post')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk__comment__user_id__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__comment'))
    )
    op.create_index(op.f('ix__comment__emotion_id'), 'comment', ['emotion_id'], unique=False)
    op.create_index(op.f('ix__comment__id'), 'comment', ['id'], unique=False)
    op.create_index(op.f('ix__comment__post_id'), 'comment', ['post_id'], unique=False)
    op.create_index(op.f('ix__comment__user_id'), 'comment', ['user_id'], unique=False)
    op.alter_column('emotion', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix__user__username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__user__username'), table_name='user')
    op.drop_column('user', 'username')
    op.alter_column('emotion', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index(op.f('ix__comment__user_id'), table_name='comment')
    op.drop_index(op.f('ix__comment__post_id'), table_name='comment')
    op.drop_index(op.f('ix__comment__id'), table_name='comment')
    op.drop_index(op.f('ix__comment__emotion_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix__status__value'), table_name='status')
    op.drop_index(op.f('ix__status__user_id'), table_name='status')
    op.drop_index(op.f('ix__status__id'), table_name='status')
    op.drop_index(op.f('ix__status__emotion_id'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix__calendar_day__user_id'), table_name='calendar_day')
    op.drop_index(op.f('ix__calendar_day__id'), table_name='calendar_day')
    op.drop_index(op.f('ix__calendar_day__emotion_id'), table_name='calendar_day')
    op.drop_index(op.f('ix__calendar_day__day'), table_name='calendar_day')
    op.drop_table('calendar_day')
    # ### end Alembic commands ###
